name: NODE CLI

on:
  push:
    branches: ["main", "feature/**", "fix/**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # Updated version

      - name: Setup Node.js
        uses: actions/setup-node@v6 # Updated version
        with:
          node-version: 22 # Use the stable LTS (22) or 24/25 if required

      - name: Install dependencies
        run: npm install # Lowercase 'i'

      - name: Run app (basic check)
        run: |
          node src/index.js & 
          sleep 5 
          kill $! # This starts it, waits 5 seconds, then closes it cleanly
