name: NODE CLI

on:
  push:
    branches: ["main", "feature/**", "fix/**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install dependencies
        run: npm Install

      - name: Run app (basic check)
        run: node src/index.js &
